### ISSUE TITLE
csv name attribute missing UI label and help text

### ISSUE THREAD

**Issue by mans0954** [Evolveum/connector-csv#4]
When viewing the Configuration tab of the Connector wizard, one of the fields is shown without a human-readable label or help text. `UI_CSV_NAME_ATTRIBUTE` is shown as the label.

It appears that the definitions of `UI_CSV_NAME_ATTRIBUTE` and `UI_CSV_NAME_ATTRIBUTE_HELP` are missing from the file `src/main/resources/com/evolveum/polygon/connector/csv/Messages.properties`.

Thanks.

**Comment by PetrGasparik** [comment]
Thanks for spotting that! 
Can you contribute?

**Comment by mans0954** [comment]
If you have some text in mind, then I can add it to the file and submit a pull request.

**Comment by PetrGasparik** [comment]
Name attribute
Name attribute for account in a resource. In most cases, it is equal to unique attribute, but there can be differences (for example, there can be autogenerated id for unique attribute and email addres for name attribute)
